version: '3.8'
services:
  app:
    container_name: Woocommerce
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge