services:
  linx-node-app:
    build: .
    ports:
      - "3001:3001"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      ACCESS_CONTROL_ALLOW_ORIGIN: ${ACCESS_CONTROL_ALLOW_ORIGIN}
      SSL: ${SSL}
      DIALECT_OPTIONS: ${DIALECT_OPTIONS}
      wcURL: ${wcURL}
      wcConsumerKey: ${wcConsumerKey}
      wcConsumerSecret: ${wcConsumerSecret}
      wcVersion: ${wcVersion}
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: ${DB_PORT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks: 
      - linx-mysql-network
networks:
  linx-mysql-network:
    external: true            